export interface PropertyRow {
  id: string;
  workspace_id?: string;
  title?: string;
  country?: string;
  city?: string;
  area?: string;
  address?: string;
  price?: string;
  currency?: string;
  price_range?: string;
  price_unit?: string;
  price_per_unit?: string;
  booking_amount?: string;
  maintenance_charges?: string;
  payment_plan?: string;
  property_type?: string;
  listing_type?: string;
  status?: string;
  bedrooms?: string | number;
  bathrooms?: string | number;
  balconies?: string;
  size?: string;
  area_unit?: string;
  floor?: string;
  total_floors?: string;
  furnishing?: string;
  parking?: string;
  facing?: string;
  possession_status?: string;
  description?: string;
  image_url?: string;
  gallery_images?: string[];
  nearby_places?: string[];
  location_advantages?: string[];
  ownership_type?: string;
  rera_status?: string;
  verification_status?: string;
  visibility?: string;
  priority?: string;
  tags?: string[];
  amenities?: string[];
  ai_summary?: string;
  ai_investment_note?: string;
  best_buyer_type?: string;
  rental_yield?: number | string;
  appreciation_forecast?: number | string;
  investor_fit?: string;
  risk_level?: string;
  roi_score?: number;
  trust_score?: number;
  developer_name?: string;
  assigned_broker?: string;
  is_featured?: boolean;
  is_hot_deal?: boolean;
  is_global_property?: boolean;
  verified?: boolean;
  roi?: number;
  created_at?: string;
  updated_at?: string;
}

