import type { MarketZone } from "./market-map-types";

/** Global market locations — coordinates approximate city centers / districts. */
export const SEED_MARKET_ZONES: MarketZone[] = [
  {
    id: "dz-marina",
    areaName: "Dubai Marina",
    country: "UAE",
    city: "Dubai",
    lat: 25.0805,
    lng: 55.1398,
    opportunityScore: 91,
    demandScore: 86,
    rentalDemand: 88,
    priceGrowthForecast: 9.2,
    investorActivity: 84,
    liquidityScore: 82,
    riskScore: 28,
    averagePrice: 2_450_000,
    currency: "AED",
    rentalYield: 7.2,
    bestPropertyType: "Apartment",
    bestBuyerType: "Cross-border investor",
    aiRecommendation: "Prioritize waterfront inventory with marina views; bundle short-let analytics for HNWI buyers.",
    lastUpdated: Date.now(),
    status: "active",
    investmentGoal: "Rental Yield",
    riskLevel: "Low",
    timeHorizon: "3-5 years",
  },
  {
    id: "dz-downtown",
    areaName: "Downtown Dubai",
    country: "UAE",
    city: "Dubai",
    lat: 25.1972,
    lng: 55.2744,
    opportunityScore: 87,
    demandScore: 80,
    rentalDemand: 76,
    priceGrowthForecast: 8.1,
    investorActivity: 88,
    liquidityScore: 78,
    riskScore: 32,
    averagePrice: 3_200_000,
    currency: "AED",
    rentalYield: 6.4,
    bestPropertyType: "Apartment",
    bestBuyerType: "Luxury end-user",
    aiRecommendation: "Highlight Burj adjacency and trophy-asset scarcity; pair with concierge rental projections.",
    lastUpdated: Date.now(),
    status: "active",
    investmentGoal: "Capital Growth",
    riskLevel: "Medium",
    timeHorizon: "5-10 years",
  },
  {
    id: "in-noida-150",
    areaName: "Noida Sector 150",
    country: "India",
    city: "Noida",
    lat: 28.4962,
    lng: 77.4756,
    opportunityScore: 78,
    demandScore: 74,
    rentalDemand: 70,
    priceGrowthForecast: 11.4,
    investorActivity: 72,
    liquidityScore: 64,
    riskScore: 48,
    averagePrice: 18_500_000,
    currency: "INR",
    rentalYield: 4.1,
    bestPropertyType: "Apartment",
    bestBuyerType: "Domestic investor",
    aiRecommendation: "Emphasize expressway connectivity and metro pipeline; stress-test EMI sensitivity for buyers.",
    lastUpdated: Date.now(),
    status: "active",
    investmentGoal: "Balanced",
    riskLevel: "Medium",
    timeHorizon: "3-5 years",
  },
  {
    id: "in-gurgaon-gcr",
    areaName: "Gurugram Golf Course Road",
    country: "India",
    city: "Gurugram",
    lat: 28.4432,
    lng: 77.1006,
    opportunityScore: 82,
    demandScore: 79,
    rentalDemand: 73,
    priceGrowthForecast: 10.2,
    investorActivity: 80,
    liquidityScore: 71,
    riskScore: 42,
    averagePrice: 42_000_000,
    currency: "INR",
    rentalYield: 4.8,
    bestPropertyType: "Villa",
    bestBuyerType: "HNI / family office",
    aiRecommendation: "Lead with gated community scarcity and golf-front premiums; add NRI tax brief.",
    lastUpdated: Date.now(),
    status: "active",
    investmentGoal: "Capital Growth",
    riskLevel: "Medium",
    timeHorizon: "5-10 years",
  },
  {
    id: "uk-canary",
    areaName: "London Canary Wharf",
    country: "UK",
    city: "London",
    lat: 51.5054,
    lng: -0.0235,
    opportunityScore: 76,
    demandScore: 68,
    rentalDemand: 72,
    priceGrowthForecast: 5.8,
    investorActivity: 74,
    liquidityScore: 76,
    riskScore: 38,
    averagePrice: 720_000,
    currency: "GBP",
    rentalYield: 4.9,
    bestPropertyType: "Mixed-Use",
    bestBuyerType: "Institutional + professional",
    aiRecommendation: "Anchor narrative on Crossrail liquidity and rental depth; monitor rate sensitivity weekly.",
    lastUpdated: Date.now(),
    status: "watch",
    investmentGoal: "Balanced",
    riskLevel: "Medium",
    timeHorizon: "5-10 years",
  },
  {
    id: "us-manhattan",
    areaName: "New York Manhattan",
    country: "USA",
    city: "New York",
    lat: 40.758,
    lng: -73.9855,
    opportunityScore: 74,
    demandScore: 71,
    rentalDemand: 78,
    priceGrowthForecast: 6.2,
    investorActivity: 81,
    liquidityScore: 79,
    riskScore: 44,
    averagePrice: 1_850_000,
    currency: "USD",
    rentalYield: 4.2,
    bestPropertyType: "Apartment",
    bestBuyerType: "Global investor",
    aiRecommendation: "Pair co-op vs condo liquidity matrix; emphasize rent-stabilized vs free-market mix.",
    lastUpdated: Date.now(),
    status: "active",
    investmentGoal: "Capital Growth",
    riskLevel: "High",
    timeHorizon: "1-3 years",
  },
  {
    id: "sg-central",
    areaName: "Singapore Central",
    country: "Singapore",
    city: "Singapore",
    lat: 1.2897,
    lng: 103.8501,
    opportunityScore: 85,
    demandScore: 77,
    rentalDemand: 74,
    priceGrowthForecast: 7.1,
    investorActivity: 79,
    liquidityScore: 88,
    riskScore: 22,
    averagePrice: 2_100_000,
    currency: "SGD",
    rentalYield: 3.8,
    bestPropertyType: "Apartment",
    bestBuyerType: "Wealth preservation buyer",
    aiRecommendation: "Stress core vs OCR arbitrage; lead with policy stability and currency hedge narrative.",
    lastUpdated: Date.now(),
    status: "active",
    investmentGoal: "Balanced",
    riskLevel: "Low",
    timeHorizon: "5-10 years",
  },
  {
    id: "ca-toronto",
    areaName: "Toronto Downtown",
    country: "Canada",
    city: "Toronto",
    lat: 43.6481,
    lng: -79.3802,
    opportunityScore: 80,
    demandScore: 75,
    rentalDemand: 81,
    priceGrowthForecast: 7.6,
    investorActivity: 73,
    liquidityScore: 77,
    riskScore: 36,
    averagePrice: 980_000,
    currency: "CAD",
    rentalYield: 4.6,
    bestPropertyType: "Apartment",
    bestBuyerType: "Immigration-led buyer",
    aiRecommendation: "Tie to population growth and rental absorption; watch stress-test on mortgage qualifying rate.",
    lastUpdated: Date.now(),
    status: "active",
    investmentGoal: "Rental Yield",
    riskLevel: "Low",
    timeHorizon: "3-5 years",
  },
];
